# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170809_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('A', 'Администратор'), ('T', 'Учитель'), ('S', 'Студент')], default='T', max_length=1),
        ),
    ]
