# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170813_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilegroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя группы'),
        ),
    ]
