# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170813_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
