# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, default=''),
        ),
    ]
