# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170814_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('U', 'Обычный урок'), ('T', 'Тестирование'), ('E', 'Пробный')], default='U', max_length=1, verbose_name='Тип'),
        ),
    ]
