# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170814_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='reason_for_presence',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
