# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170814_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='mark',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='', max_length=1),
        ),
    ]
