# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20170814_0349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlesson',
            old_name='reason_for_precence',
            new_name='reason_for_precense',
        ),
    ]
