# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20170814_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата урока'),
        ),
        migrations.AlterField(
            model_name='studentlesson',
            name='mark',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('-', '-')], default='', max_length=1),
        ),
    ]
