# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170815_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название курса'),
        ),
    ]
